---
- stat: path=/etc/php/5.6/fpm/php.ini
  register: phpfpm

- stat: path=/etc/php/5.6/cli/php.ini
  register: phpcli

- stat: path=/etc/php/5.6/apache2/php.ini
  register: phpapachemod

- include: php-fpm.yml
  when: phpfpm.stat.exists

- include: php-cli.yml
  when: phpcli.stat.exists

- include: php-apache2.yml
  when: phpapachemod.stat.exists