---
 - name: Permissão de pasta
   file: path={{ configs.vm_path }} state=directory owner=www-data group=www-data mode=0775
   become: yes
   become_method: sudo

 - name: Permissão de uso da Storage
   file: path={{ configs.vm_path }}/storage state=directory mode=0777
   become: yes
   become_method: sudo

 - name: Check Env
   stat: path={{ configs.vm_path }}/.env
   register: env_file

 - name: Copia arquivo Env
   become: yes
   become_method: sudo
   shell: echo "APP_ENV=local\n" > {{ configs.vm_path }}/.env \
          "APP_KEY=\n" >> {{ configs.vm_path }}/.env \
          "APP_DEBUG=true\n" >> {{ configs.vm_path }}/.env \
          "APP_LOG_LEVEL=debug\n" >> {{ configs.vm_path }}/.env \
          "APP_URL=http://{{ configs.vm_url }}\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env \
          "DB_CONNECTION=mysql\n" >> {{ configs.vm_path }}/.env \
          "DB_HOST=127.0.0.1\n" >> {{ configs.vm_path }}/.env \
          "DB_PORT=3306\n" >> {{ configs.vm_path }}/.env \
          "DB_DATABASE={{ mysql.database }}\n" >> {{ configs.vm_path }}/.env \
          "DB_USERNAME={{ mysql.user }}\n" >> {{ configs.vm_path }}/.env \
          "DB_PASSWORD={{ mysql.password }}\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env \
          "BROADCAST_DRIVER=log\n" >> {{ configs.vm_path }}/.env \
          "CACHE_DRIVER=file\n" >> {{ configs.vm_path }}/.env \
          "SESSION_DRIVER=file\n" >> {{ configs.vm_path }}/.env \
          "QUEUE_DRIVER=sync\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env \
          "REDIS_HOST=127.0.0.1\n" >> {{ configs.vm_path }}/.env \
          "REDIS_PASSWORD=null\n" >> {{ configs.vm_path }}/.env \
          "REDIS_PORT=6379\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env \
          "MAIL_DRIVER=smtp\n" >> {{ configs.vm_path }}/.env \
          "MAIL_HOST=mailtrap.io\n" >> {{ configs.vm_path }}/.env \
          "MAIL_PORT=2525\n" >> {{ configs.vm_path }}/.env \
          "MAIL_USERNAME=null\n" >> {{ configs.vm_path }}/.env \
          "MAIL_PASSWORD=null\n" >> {{ configs.vm_path }}/.env \
          "MAIL_ENCRYPTION=null\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env \
          "PUSHER_APP_ID=\n" >> {{ configs.vm_path }}/.env \
          "PUSHER_KEY=\n" >> {{ configs.vm_path }}/.env \
          "PUSHER_SECRET=\n" >> {{ configs.vm_path }}/.env \
          "\n" >> {{ configs.vm_path }}/.env
   when: env_file.stat.exists == False

 - name: Permissão de uso da Storage
   file: path={{ configs.vm_path }}/bootstrap/cache/ state=directory mode=0777
   become: yes
   become_method: sudo

 - name: Install Composer on Project
   composer: command=install working_dir={{ configs.vm_path }}

 - name: Install Migrations and seeds
   shell: php artisan migrate --seed
   args:
    chdir: "{{ configs.vm_path }}"