---
 - name: Permissão de pasta
   file: path={{ configs.vm_path }} state=directory owner=www-data group=www-data mode=0775
   become: yes
   become_method: sudo

 - name: Permissão de uso da Storage
   file: path={{ configs.vm_path }}/storage state=directory mode=0777
   become: yes
   become_method: sudo

 - name: Check Env
   stat: path={{ configs.vm_path }}/.env
   register: env_file

 - name: Copia arquivo Env
   become: yes
   become_method: www-data
   shell: echo "APP_ENV=local" > .env \
          echo "APP_KEY=" >> .env \
          echo "APP_DEBUG=true" >> .env \
          echo "APP_LOG_LEVEL=debug" >> .env \
          echo "APP_URL={{ configs.vm_url }}" >> .env \
          echo "" >> .env \
          echo "DB_CONNECTION=mysql" >> .env \
          echo "DB_HOST=127.0.0.1" >> .env \
          echo "DB_PORT=3306" >> .env \
          echo "DB_DATABASE={{ mysql.database }}" >> .env \
          echo "DB_USERNAME={{ mysql.user }}" >> .env \
          echo "DB_PASSWORD={{ mysql.password }}" >> .env \
          echo "" >> .env \
          echo "BROADCAST_DRIVER=log" >> .env \
          echo "CACHE_DRIVER=file" >> .env \
          echo "SESSION_DRIVER=file" >> .env \
          echo "QUEUE_DRIVER=sync" >> .env \
          echo "" >> .env \
          echo "REDIS_HOST=127.0.0.1" >> .env \
          echo "REDIS_PASSWORD=null" >> .env \
          echo "REDIS_PORT=6379" >> .env \
          echo "" >> .env \
          echo "MAIL_DRIVER=smtp" >> .env \
          echo "MAIL_HOST=mailtrap.io" >> .env \
          echo "MAIL_PORT=2525" >> .env \
          echo "MAIL_USERNAME=null" >> .env \
          echo "MAIL_PASSWORD=null" >> .env \
          echo "MAIL_ENCRYPTION=null" >> .env \
          echo "" >> .env \
          echo "PUSHER_APP_ID=" >> .env \
          echo "PUSHER_KEY=" >> .env \
          echo "PUSHER_SECRET=" >> .env
   #copy: src={{ configs.vm_path }}/.env.vagrant dest={{ configs.vm_path }}/.env owner=www-data group=www-data mode=0644
   when: env_file.stat.exists == False

 - name: Permissão de uso da Storage
   file: path={{ configs.vm_path }}/bootstrap/cache/ state=directory mode=0777
   become: yes
   become_method: sudo

 - name: Install Composer on Project
   composer: command=install working_dir={{ configs.vm_path }}

 - name: Install Migrations and seeds
   shell: php artisan migrate --seed
   args:
    chdir: "{{ configs.vm_path }}"