---
molecule:
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
    - venv

ansible:
  playbook: playbook.yml

docker:
  containers:
  - name: nodejs-01
    image: ubuntu
    image_version: xenial
  - name: nodejs-02
    image: ubuntu
    image_version: trusty

verifier:
  name: testinfra
