---
galaxy_info:
  author: Rodrigo Tschope Based on Arkadiusz Kondas
  description: Installs and configure PHP 5 on Debian/Ubuntu servers
  license: MIT
  min_ansible_version: 1.0
  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - php
    - php56
    - web