---
# - name: mkdir .wp-cli
#   file: path={{ wp_cli_dir }} state=directory owner=vagrant group=vagrant

# - name: create a composer.json
#   command: chdir={{ wp_cli_dir }} {{ composer }} init --stability dev --no-interaction
# - name: create a composer.json
#   command: chdir={{ wp_cli_dir }} {{ composer }} config bin-dir bin
# - name: create a composer.json
#   command: chdir={{ wp_cli_dir }} {{ composer }} config vendor-dir vendor

# - name: add WP-CLI package index
#   command: chdir={{ wp_cli_dir }} {{ composer }} config repositories.wp-cli composer 'http://wp-cli.org/package-index/'

# - name: create a config.yml
#   template: src=config.yml.j2 dest=/home/vagrant/.wp-cli/config.yml owner=vagrant

# - name: WP-CLI Package installed
#   command: chdir={{ wp_cli_dir }} {{ composer }} require {{ item }}=dev-master
#   with_items:
#     - danielbachhuber/dictator

# - name: change owner and group
#   file: dest={{ wp_cli_dir }} state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
#   sudo: yes
